#!/bin/bash
current_dir=$(pwd); parent_dir=$(dirname "$current_dir") for file in *.html do destination="$parent_dir/$file" if [ ! -e "$destination" ]  [ "$file" -nt "$destination" ] then cp "$file" "$destination"; echo "Copied $file to $destination" fi done

